services:
  weather-ussd:
    build: .
    image: weather-ussd:1.0
    container_name: weather-ussd
    restart: unless-stopped
    env_file: .env
    ports:
      - "8080:8080"
    volumes:
      - ./data:/weather-ussd/data
      - ./logs:/weather-ussd/logs
